### PR TITLE
Add feature_redraw_interval option

### PR DESCRIPTION
**Pull request by norabelrose**
This fork allows the user to select a number of forward passes after which the random features will be redrawn. This allows us to avoid doing QR decomposition on the CPU every forward pass. By default it is set to redraw every 1000 passes.

### CODE REVIEW

**Comment by norabelrose** [comment]
By the way, I went ahead and compared the two algorithms (one which redraws features every time and one which only redraws every 1000 passes) over 10k trials. At least with d_model = 768, num_heads = 12, seq_len = 1000, we get a dramatic 5-6x speedup. It's clear that the model is spending most of its time doing QR decomposition.
Captura de Pantalla 2020-11-20 a la(s) 1 19 38 a  m

Here's another run where I told my algorithm to redraw every time:
Captura de Pantalla 2020-11-20 a la(s) 1 11 38 a  m
We see that now both are slow.

And finally, when I use this fork of Performer PyTorch, with feature_redraw_interval = 1000, both get the same good performance:
Captura de Pantalla 2020-11-20 a la(s) 1 28 23 a  m

**Comment by lucidrains** [comment]
@norabelrose hi Nora! Thank you for taking the time to do this!

Have you measured how the redraw interval impacted training for your task?

**Comment by norabelrose** [comment]
@lucidrains No problem! I haven’t had a chance to do so yet, but I should be able to in the next day or so when I fine tune DistilBERT for FAVOR+. Will let you know what I find. DistilBERT has d_model=768, num_heads=12, so the results should be similar.

**Comment by lucidrains** [comment]
@norabelrose Sounds good! Figure 5 (right figure) in the paper seems to show that without redraws, it does not converge, but I wonder how frequently one needs to draw

do let me know, and if it works well, I shall accept your generous contribution lol

**Comment by lucidrains** [comment]
@norabelrose the other thing i've been meaning to try is to see if the numpy QR decomposition is any faster (and then just .from_numpy it into pytorch)

**Comment by norabelrose** [comment]
Just did the trials testing torch vs. NumPy QR decomposition. I actually wasn't expecting this.

When you do everything in 100% NumPy, it's dramatically faster:
Captura de Pantalla 2020-11-20 a la(s) 9 29 58 a  m

Switching from PyTorch to NumPy and back again slows things down quite a bit, but NumPy is still ~2x faster:
Captura de Pantalla 2020-11-20 a la(s) 9 34 59 a  m

**Comment by lucidrains** [comment]
There's also https://docs.cupy.dev/en/stable/reference/generated/cupy.linalg.qr.html and then https://discuss.pytorch.org/t/convert-torch-tensors-directly-to-cupy-tensors/2752/5

**Comment by lucidrains** [comment]
@norabelrose just read your comment in the issues and you are right, I misunderstood the redraw projections

**Pull request merged**
